from src.core.settings import settings

APP_NAME = settings.APP_NAME
VERSION = settings.VERSION
AUTHOR = settings.AUTHOR

DEBUG = settings.DEBUG

DATABASE_NAME = settings.DATABASE_NAME
DATABASE_URL = settings.DATABASE_URL

AI_ENGINE = settings.AI_ENGINE

JWT_SECRET_KEY = settings.JWT_SECRET_KEY
JWT_ALGORITHM = settings.JWT_ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = settings.ACCESS_TOKEN_EXPIRE_MINUTES
REFRESH_TOKEN_EXPIRE_DAYS = settings.REFRESH_TOKEN_EXPIRE_DAYS
